services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/data
    ports:
      - "5432:5432"


